# 站点设置
title: Broleez 的个人博客
description: 欢迎访问我的个人博客
baseurl: ""
url: "https://broleez.github.io"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 博客设置
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# 作者信息
author:
  name: Broleez
  email: broleez.ml@gmail.com

# 导航菜单
header_pages:
  - about.md
  - archive.md
  - resume.md

# 内容集合
collections:
  notes:
    output: true
    permalink: /notes/:title/
  projects:
    output: true
    permalink: /projects/:title/
  books:
    output: true
    permalink: /books/:title/
  tutorials:
    output: true
    permalink: /tutorials/:title/

# 默认布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "books"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "post"
      comments: true